/// <summary>
/// Enum used bo passive abilities.
/// </summary>
public enum PassiveType
{
    Health,
    Mana,
    MovementSpeed,
    CriticalChance,
    CriticalDamage,
    IgnisDamage,
    FulgurDamage,
    AquaDamage,
    TerraDamage,
    NaturaDamage,
    LuxDamage,
    UmbraDamage,
    IgnisFulgurDamage,
    IgnisAquaDamage,
    IgnisTerraDamage,
    IgnisNaturaDamage,
    IgnisLuxDamage,
    IgnisUmbraDamage,
    FulgurAquaDamage,
    FulgurTerraDamage,
    FulgurNaturaDamage,
    FulgurLuxDamage,
    FulgurUmbraDamage,
    AquaTerraDamage,
    AquaNaturaDamage,
    AquaLuxDamage,
    AquaUmbraDamage,
    TerraNaturaDamage,
    TerraLuxDamage,
    TerraUmbraDamage,
    NaturaLuxDamage,
    NaturaUmbraDamage,
    LuxUmbraDamage,
}
